properties:
  id:
    type: string
    minLength: 1
    required: true
  geometry:
    type: geometry
    required: true
  bbox:
    type: bounding-box
  area:
    type: uint32
    exclusiveMinimum: 0
    maximum: 1000000000
  datetime:
    type: date-time
  expires:
    type: date-time
